# Starter pipeline
# Minimal pipeline that you can customize to build and deploy your code.
# Steps to build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- {{ branch }}

pool:
  {{ pool }}

steps:
- script: echo Hello, Azure DevOps!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
